# Dokumentation Schulung LPIC-1

## Montag

- Geschichte von Linux
- Manpages -> `man <kommando>` 
- grundlegende Kommandos (BASH):

---- 
touch
ls
cd
rm
mkdir
apropos
whereis
info
---- 

- Aufbau von Kommandos:

----
kommando [-o/--option]... [argument]...
----

## Dienstag

- Befehle Dateiverwaltung:
----
cp
cp  -r (rekursiv)
cp -a
mv
mv (kein -r noetig)
rm
rm -r
----

- absolute (beginnen immer mit einem `/`) und relative Pfadangaben
- Sonderzeichen: `*`, `?`, ` ` (Leerzeichen)
- Escapen von Sonderzeichen
- Suche innerhalb der Manpages
- Variablen (Vererbung/Subshells)
- Kommando `export`
- Ausgabe des Inhalts von Variablen mit `echo $varname`
- Kommanod `env`
- `git`

## Mittoch

- Aufbau Shell-Prompt (Variable `PS1`)
- Definition eigener Aliase (in `.bash_aliases`)
- "Sicherheitseinstellungen" für `cp`, `rm` und `mv` (`-i`)
- Shell Builtins / externe Kommandos
- Pipe `|`
- `less`: Seitenweises Anzeigen von Dateien/Textstroemen
- persoenliche / systemweite Konfigurationsdateien: z.B. `~/.bashrc` bzw. `/etc/bash.bashrc`
- `!$`: hiermit kann das letzte Argument des zuletzt eingegebenen Kommandos aufgerufen werden:

----
# Datei editieren
nano ~/.bash_aliase

# Datei sourcen
. !$
source !$
----

- Verzeichnisse: 
  - `home`: beinhaltet die Heimatverzeichnisse der Benutzer
  - `etc`: beinhaltet *alle* systemweiten Konfigurationsdateien
  - `root`: Heimatverzeichnis des Benutzers `root`
  - `boot`: Dateien für den Bootloader, Linux Kernel etc.
- Kommanodsubstitution:
  - `echo $(kommando)`: kommando wird ausgeführt und das Ergebnis von `echo` ausgegeben
- `grep` sucht nach Suchbegriffen innerhalb von Dateien

### Textstroeme, Filter und Umleitungen
- Standardkanäle:
  - `stdin`: Kanal 0 - Eingabekanal 
  - `stdout`: Kanal 1 - Ausgabkanal 
  - `stderr`: Kanal 2 - Fehlerkanal 
- Umleitungen / Redirects:
  - Kanäle koennen in andere Kanaele oder Dateien umgeleitet werden
  - `>` Dateiinhalt wird ersetzt
  - `>>` neue Ausgabe wird an bestehende Datei angehängt
- Pipes `|`
  - die Ausgabe (Kanal 1) eines Kommandos wird an die Eingabe (Kanal 0) eines weiteren Programms geleitet

### UNIX Philosophie
- Schreibe Computerprogramme so, dass sie nur eine Aufgabe erledigen und diese gut machen.
- Schreibe Programme so, dass sie zusammenarbeiten.
- Schreibe Programme so, dass sie Textströme verarbeiten, denn das ist eine universelle Schnittstelle.
- vereinfacht: Mache nur eine Sache und mache sie gut.

## Donnerstag

### Berechtigungen

----
# reguläre Dateien
r = read    -> Dateiinhalt lesen
w = write   -> Dateiinhalt schreiben
x = execute -> Dateien ausführen 

# Verzeichnisse
r = read    -> Verzeichnisinhalt lesen
w = write   -> Dateien erstellen oder loeschen
x = execute -> Verzeichnis betreten/hineinwechseln

Filedescriptor Owner Group Others
                u      g    o
-	       rwx   rwx   rwx 
----

### Berechtigungen ändern

Der Besitzer einer Datei (oder `root`) koennen mit dem Kommando `chmod` Berechtigungen ändern

#### Symbolische Rechtevergabe

----
# (< und > sind Platzhalter)

chmod <user,group,other,all>+-=<read,write,execute> datei

chmod <u,g,o,a>+-=<r,w,e> datei

chmod u+w datei    # Schreibrecht für Besitzer hinzufügen

chmod g-rw datei   # Gruppe Lese- und Schreibrecht entziehen
chmod ug+rwx datei  # User und Gruppe alle Rechte hinzufügen
----


#### Oktale Rechtevergabe

----
 r = 4
 w = 2
 x = 1

 dez bin
 1   001
 2   010
 4   100


  6      5    
 rwx    rwx
 110    101
----

- Rechte koennen nur absolut, d.h. für Besitzer, Gruppe und Others gleichzeitig vergeben werden
- jedes Recht hat einen eigenen Wert
- Rechte werden über die Addition der Einzelwerte angesprochen
- Lese- und Schreibrecht resultiert also in der Addition von 4 (lesen) plus 2 (schreiben) -> 6 

### Gruppen

- es gibt zwei Arten von Gruppen: die initiale/primäre Gruppe eines Benutzers (heisst in der Regel genauso wie der Benutzer) und die zusätzlichen (suplementary) Gruppen
- wenn man einen Benutzer einer Gruppe hinzufügt, muss sich dieser einmal komplett ab- und wieder anmelden, damit die Gruppenzugehoerigkeit aktiv wird (Konfigurationsdatei `/etc/group` wird dann neu eingelesen


### sudo
- um einem Benutzer sudo-Rechte zu gewähren, kann dieser z.B. in die Gruppe `sudo` oder `wheel` (distributionsabhängig) hinzugefügt werden





