# Dokumentation Schulung LPIC-1

## Montag

- Geschichte von Linux
- Manpages -> `man <kommando>` 
- grundlegende Kommandos (BASH):

---- 
touch
ls
cd
rm
mkdir
apropos
whereis
info
---- 

- Aufbau von Kommandos:

----
kommando [-o/--option]... [argument]...
----

## Dienstag

- Befehle Dateiverwaltung:
----
cp
cp  -r (rekursiv)
cp -a
mv
mv (kein -r noetig)
rm
rm -r
----

- absolute (beginnen immer mit einem `/`) und relative Pfadangaben
- Sonderzeichen: `*`, `?`, ` ` (Leerzeichen)
- Escapen von Sonderzeichen
- Suche innerhalb der Manpages
- Variablen (Vererbung/Subshells)
- Kommando `export`
- Ausgabe des Inhalts von Variablen mit `echo $varname`
- Kommanod `env`
- `git`

## Mittoch

- Aufbau Shell-Prompt (Variable `PS1`)
- Definition eigener Aliase (in `.bash_aliases`)
- "Sicherheitseinstellungen" für `cp`, `rm` und `mv` (`-i`)
- Shell Builtins / externe Kommandos
- Pipe `|`
- `less`: Seitenweises Anzeigen von Dateien/Textstroemen
- persoenliche / systemweite Konfigurationsdateien: z.B. `~/.bashrc` bzw. `/etc/bash.bashrc`
- `!$`: hiermit kann das letzte Argument des zuletzt eingegebenen Kommandos aufgerufen werden:

----
# Datei editieren
nano ~/.bash_aliase

# Datei sourcen
. !$
source !$
----

- Verzeichnisse: 
  - `home`: beinhaltet die Heimatverzeichnisse der Benutzer
  - `etc`: beinhaltet *alle* systemweiten Konfigurationsdateien
  - `root`: Heimatverzeichnis des Benutzers `root`
  - `boot`: Dateien für den Bootloader, Linux Kernel etc.
- Kommanodsubstitution:
  - `echo $(kommando)`: kommando wird ausgeführt und das Ergebnis von `echo` ausgegeben
- `grep` sucht nach Suchbegriffen innerhalb von Dateien

### Textstroeme, Filter und Umleitungen
- Standardkanäle:
  - `stdin`: Kanal 0 - Eingabekanal 
  - `stdout`: Kanal 1 - Ausgabkanal 
  - `stderr`: Kanal 2 - Fehlerkanal 
- Umleitungen / Redirects:
  - Kanäle koennen in andere Kanaele oder Dateien umgeleitet werden
  - `>` Dateiinhalt wird ersetzt
  - `>>` neue Ausgabe wird an bestehende Datei angehängt
- Pipes `|`
  - die Ausgabe (Kanal 1) eines Kommandos wird an die Eingabe (Kanal 0) eines weiteren Programms geleitet

### UNIX Philosophie
- Schreibe Computerprogramme so, dass sie nur eine Aufgabe erledigen und diese gut machen.
- Schreibe Programme so, dass sie zusammenarbeiten.
- Schreibe Programme so, dass sie Textströme verarbeiten, denn das ist eine universelle Schnittstelle.
- vereinfacht: Mache nur eine Sache und mache sie gut.

## Donnerstag

### Berechtigungen

----
# reguläre Dateien
r = read    -> Dateiinhalt lesen
w = write   -> Dateiinhalt schreiben
x = execute -> Dateien ausführen 

# Verzeichnisse
r = read    -> Verzeichnisinhalt lesen
w = write   -> Dateien erstellen oder loeschen
x = execute -> Verzeichnis betreten/hineinwechseln

Filedescriptor Owner Group Others
                u      g    o
-	       rwx   rwx   rwx 
----

### Berechtigungen ändern

Der Besitzer einer Datei (oder `root`) koennen mit dem Kommando `chmod` Berechtigungen ändern

#### Symbolische Rechtevergabe

----
# (< und > sind Platzhalter)

chmod <user,group,other,all>+-=<read,write,execute> datei

chmod <u,g,o,a>+-=<r,w,e> datei

chmod u+w datei    # Schreibrecht für Besitzer hinzufügen

chmod g-rw datei   # Gruppe Lese- und Schreibrecht entziehen
chmod ug+rwx datei  # User und Gruppe alle Rechte hinzufügen
----


#### Oktale Rechtevergabe

----
 r = 4
 w = 2
 x = 1

 dez bin
 1   001
 2   010
 4   100


  6      5    
 rwx    rwx
 110    101
----

- Rechte koennen nur absolut, d.h. für Besitzer, Gruppe und Others gleichzeitig vergeben werden
- jedes Recht hat einen eigenen Wert
- Rechte werden über die Addition der Einzelwerte angesprochen
- Lese- und Schreibrecht resultiert also in der Addition von 4 (lesen) plus 2 (schreiben) -> 6 

### Gruppen

- es gibt zwei Arten von Gruppen: die initiale/primäre Gruppe eines Benutzers (heisst in der Regel genauso wie der Benutzer) und die zusätzlichen (suplementary) Gruppen
- wenn man einen Benutzer einer Gruppe hinzufügt, muss sich dieser einmal komplett ab- und wieder anmelden, damit die Gruppenzugehoerigkeit aktiv wird (Konfigurationsdatei `/etc/group` wird dann neu eingelesen


### sudo
- um einem Benutzer sudo-Rechte zu gewähren, kann dieser z.B. in die Gruppe `sudo` oder `wheel` (distributionsabhängig) hinzugefügt werden

### curl / wget
- CLI Programme zum Herunterladen ganzer Webseiten, Dateien, Bilder etc.
- Koennen auch zur Prüfung der Erreichbarkeit von Webseiten eingesetzt werden


## Montag

### 101.1 Hardwareeinstellungen / Boot Prozess

#### Komponenten Boot
1. Anschalten
2. BIOS (Basis Input Output System) / UEFI (Unified Extensible Firmware Interface) 
3. Power On Self Test (POST): grundlegender Hardwaretest
4. Bootloader (GRUB oder anderer)
5. OS (Linux-Kernel) wird gestartet
6. Kernelspace -> Userspace (`init` / `systemd`)

#### PCI

- `lspci` - Liste aller am PCI-Bus angeschlossener Geräte
- einzelne Geräte koennen über Bus angesprochen werden

#### USB 

- `lsusb` - Liste angeschlossener USB Geräte 
- einzelne Geräte koennen über ID oder Bus angesprochen werden

##### USB 1.1
- `usb-ohci.o` -> Open Host Controller Interface
- `usb-uhci.o` -> Universal Host...

##### USB 2.0
- `usb-ehci.o` -> Enhanced ...

##### USB 3
- `usb-xhci.o` -> Extensible ...
 
##### proc/ und sys/
- hier werden zur Laufzeit Informationen über Programme/Prozesse/System an sich hinterlegt
- diese koennen meist nur eingesehen, manchmal aber auch durch einfache Schreiboperationen (z.B. mit `echo` auf die gegebene Datei verändert werden (nur für aktuellen Bootvorgang))


### Dienstag

#### 103.5 Prozesse
- Was sind Prozesse
- Vordergrung/Hintergrund `bg`, `fg`, `<kommando> &`
- Prozesse überwachen mit `ps`, `jobs`, `top`
- Signale an Prozesse senden mit
  - `kill` bzw. `killall` und `pkill`
  - Tastenkombinationen `STRG+C`, `STRG+Z`
- PID herausfinden mit `pgrep`
- Prozesse von der aktuellen Shell "loesen":
  - `nohup`
  - Terminal Multiplexer `screen` (`tmux`, `byobu`)


### Mittwoch

TODO


### Donnerstag

#### Regular Expressions

----
.       - Any Character Except New Line
\d	- Digit (0-9)
\D	- Not a Digit (every character except 0-9)
\s 	- any Whitespace (Space, Tab, Newline)
\S 	- Not a  Whitespace
\w	- Word character (a-z, A-Z, 0-9, _, -)
\W	- Not a Word character 


\b 	- word Boundary
^ 	- Zeilenanfang
$	- Zeilenende
----

##### Quantifier (act on previous symbol)
----
* 	- 0 or more
+	- 1 or more
?	- 0 or 1  /  optional
{n}	- exactly n times
{n,m}   - between n and m times
{n,}	- minimum n times
{,n}	- maximum n times
----

##### Character Sets / List of characters
----
[abc] 	- one of a, b or c
[0-9] 	- range from 0 to 9 <=> \d
[a-z] 	- range from a to z
[^a] 	- not a
|	- either or
----

##### Groups
----
()		- Group
(expr1|expr2)	- either expr1 or expr2
----


##### Examples
----
# RegEx
^\(?[0-9]{4}(\)\s|[.-])\d{6}$

# Matches
0561.807000
0561-807000
(0561) 807000

# Does not match
0561_807000
----

----
# RegEx
^https?://([a-z0-9]+\.)?([a-z0-9]+\.)?[a-z]{2,3}$
^https?://([a-z0-9]+\.)?([a-z0-9]+\.)?(de|com|org|eu)$

# matches:
https://gfn.de
https://www.gfn.de
http://mypage.com
https://www.google.eu
https://meine.haustiere.com

# does not match:
https://meine.haustiere
https://Meine.Haustiere.de
https://ätsch.de
http://_dontmatch.ch
https://*auchnicht.de
http://(nlll.lkj
https//no.org
https://gfn-de
htps:/bla.com
http://localhost
http://mocalhost
httpw://nonono
----

##### Links
- https://www.debuggex.com/  (Regex Editor mit grafischer Repräsentation)
- http://regexe.de/	(Regex Editor mit Suchen und Ersetzen)
- https://regexone.com/	(Regex Tutorial)
- https://www.regular-expressions.info/
